version: "3.7"

services:
  backend:
    image: registry.gitlab.com/castlecraft/excel_erpnext/excel-erpnext-worker:${ERPNEXT_VERSION?Variable ERPNEXT_VERSION not set}
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
    networks:
      - mariadb-network
      - bench-network

  frontend:
    image: registry.gitlab.com/castlecraft/excel_erpnext/excel-erpnext-nginx:${ERPNEXT_VERSION?Variable ERPNEXT_VERSION not set}
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.constraint-label: traefik-public
        traefik.http.routers.erpnext-v13-http.rule: Host(${SITES:?No sites set})
        traefik.http.routers.erpnext-v13-http.entrypoints: http
        traefik.http.routers.erpnext-v13-https.rule: Host(${SITES})
        traefik.http.routers.erpnext-v13-https.entrypoints: https
        traefik.http.routers.erpnext-v13-https.tls: "true"
        traefik.http.routers.erpnext-v13-https.tls.certresolver: le
        traefik.http.services.erpnext-v13.loadbalancer.server.port: "8080"
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: $$host
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    volumes:
      - sites:/usr/share/nginx/html/sites
      - assets:/usr/share/nginx/html/assets
    networks:
      - mariadb-network
      - bench-network
      - traefik-public

  queue-default:
    image: registry.gitlab.com/castlecraft/excel_erpnext/excel-erpnext-worker:${ERPNEXT_VERSION?Variable ERPNEXT_VERSION not set}
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - mariadb-network
      - bench-network

  queue-long:
    image: registry.gitlab.com/castlecraft/excel_erpnext/excel-erpnext-worker:${ERPNEXT_VERSION?Variable ERPNEXT_VERSION not set}
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - mariadb-network
      - bench-network

  queue-short:
    image: registry.gitlab.com/castlecraft/excel_erpnext/excel-erpnext-worker:${ERPNEXT_VERSION?Variable ERPNEXT_VERSION not set}
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - mariadb-network
      - bench-network

  redis-cache:
    image: redis:latest
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data
    networks:
      - bench-network

  redis-queue:
    image: redis:latest
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data
    networks:
      - bench-network

  redis-socketio:
    image: redis:latest
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    volumes:
      - redis-socketio-data:/data
    networks:
      - bench-network

  scheduler:
    image: registry.gitlab.com/castlecraft/excel_erpnext/excel-erpnext-worker:${ERPNEXT_VERSION?Variable ERPNEXT_VERSION not set}
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - mariadb-network
      - bench-network

  websocket:
    image: frappe/frappe-socketio:v13.0.0
    deploy:
      placement:
        constraints:
          - node.labels.deployment.node == erpnode
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - mariadb-network
      - bench-network

volumes:
  assets:
  db-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  sites:

networks:
  bench-network:
    name: erpnext-v13
    external: false
  mariadb-network:
    name: mariadb-network
    external: true
  traefik-public:
    name: traefik-public
    external: true


# Note: set ERPNEXT_VERSION=version-13, SITES

# bench new-site etlerp.arcapps.org --mariadb-root-password 0Xuk8MhkJWLwGj3 --admin-password 0Xuk8MhkJWLwGj3 --install-app erpnext --install-app excel_erpnext